name: continuous integration - Reusable
on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      npm_install:
        required: true
        type: boolean
    secrets:
      vault_token:
        required: true
jobs:
  CI_Steps:
    runs-on: [self-hosted]
    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: Import vault Secrets
        id: vault-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.janand.online:8200/
          token: ${{ secrets.vault_token }}
          tlsSkipVerify: true
          secrets: |
              common/data/common sonarqube_user | sonarqube_user;
              common/data/common sonarqube_password | sonarqube_password ;


      - run: echo ok
        name: code lint
#      - run: echo ok
#        name: code Build

      - run: npm install
        name: Install NodeJS modules
        if: ${{ inputs.npm_install }}

      - run: echo npm run test:unit
        name: code unit test

      - run: echo npm run test:integration
        name: code integration test

      - run: /opt/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner -Dsonar.host.url=http://sonarqube-internal.janand.online:9000 -Dsonar.projectKey=${{ inputs.project_name }} -Dsonar.qualitygate.wait=true -Dsonar.login=${{ steps.vault-secrets.outputs.sonarqube_user }} -Dsonar.password=${{ steps.vault-secrets.outputs.sonarqube_password }}
        name: code review

      - run: echo ok
        name: release software
        if: ${{ ! startwith{github.ref, 'refs/tags/*'} }}