name: continuous integration - reusable
on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
jobs:
  CI_Steps:
    runs-on: [self-hosted] #ci-runner-ec2
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - run: echo ok
        name: code link
#      - run: echo ok
#        name: code Build
      - run: npm install
        name: Install NodeJS modules
      - run: echo npm run test:unit
        name: code unit test
      - run: echo npm run test:integration
        name: code integration test
      - run: echo /opt/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner -Dsonar.host.url=http://sonarqube-internal.janand.online:9000 -Dsonar.projectKey=${{ inputs.project_name }} -Dsonar.qualitygate.wait=true -Dsonar.login=${{ steps.vault-secrets.outputs.sonarqube_user }} -Dsonar.password=${{ steps.vault-secrets.outputs.sonarqube_password }}
        name: code review
      - run: echo ok
        name: release software