name: continuous integration - reusable
on: [workflow_call]
jobs:
  CI_Steps:
    runs-on: [self-hosted] #ci-runner-ec2
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - run: echo ok
        name: code link
#      - run: echo ok
#        name: code Build
      - run: npm install
        name: Install NodeJS modules
      - run: echo npm run test:unit
        name: code unit test
      - run: echo npm run test:integration
        name: code integration test
      - run: echo ok
        name: code review
      - run: echo ok
        name: release software