name: continuous integration - Reusable
on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
    secrets:
      vault_token:
        required: true
jobs:
  CI_Steps:
    runs-on: [self-hosted]
    steps:
      - name: code checkout
        uses: actions/checkout@v4


      - run: echo ok
        name: code link
#      - run: echo ok
#        name: code Build
      - run: npm install
        name: Install NodeJS modules
      - run: echo npm run test:unit
        name: code unit test
      - run: echo npm run test:integration
        name: code integration test
      - run: echo /opt/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner -Dsonar.host.url=http://sonarqube-internal.janand.online:9000 -Dsonar.projectKey=${{ inputs.project_name }} -Dsonar.qualitygate.wait=true - ${{ secrets.vault_token }}
        name: code review
      - run: echo ok
        name: release software