name: continuous integration - reusable
on: [workflow_call]
jobs:
  CI_Steps:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
#      - run: echo ok
#        name: echo Build
      - run: echo ok
        name: echo test
      - run: echo ok
        name: echo review
      - run: echo ok
        name: release software