name: Release - Reusable
on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      release_archive_file:
        required: true
        type: string
      npm_install:
        required: true
        type: boolean
    secrets:
      vault_token:
        required: true
jobs:
  CI_Steps:
    runs-on: [self-hosted]
    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - run: echo npm install
        name: Install NodeJS modules
        if: ${{ inputs.npm_install }}

      - name: Import vault Secrets
        id: vault-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.janand.online:8200/
          token: ${{ secrets.vault_token }}
          tlsSkipVerify: true
          secrets: |
            common/data/common artifactory_user | artifactory_user;
            common/data/common artifactory_password | artifactory_password ;

      - run: echo ${GITHUB_REF_NAME} >VERSION
        name: create version file

      - name: prepare artifact
        run: zip -r artifact.zip ${{ inputs.release_archive_file }}

      - run: curl -f -v --user ${{ steps.vault-secrets.outputs.artifactory_user }}:${{ steps.vault-secrets.outputs.artifactory_password }} --data-binary @artifact.zip -X PUT "http://artifactory-internal.janand.online:8081/artifactory/${{ inputs.project_name }}/${GITHUB_REF_NAME}.zip"
        name: upload artifact

      - run: |
          echo '{
          "environment_variables": [
            {
              "name": "APP_VERSION",
              "secure": false,
              "value": "app_version"
            }
          ],
          "update_materials_before_scheduling": true
          }' | sed -e "s/app_version/${GITHUB_REF_NAME}/" | jq >data.json
          curl 'http://172.31.25.3:8153/go/api/pipelines/${{ inputs.project_name }}/schedule' -H 'Accept: application/vnd.go.cd.v1+json' -H 'Content-Type: application/json' -X POST -d "@data.json"
